FROM node:20-alpine

WORKDIR /app

# Устанавливаем простой HTTP сервер
RUN npm install -g http-server

# Копируем статику
COPY public /app/public

# Переменные окружения
ENV PORT=3000

EXPOSE 3000

# Запускаем статический сервер
CMD ["http-server", "/app/public", "-p", "3000", "--cors", "-c-1"]

